#!/usr/bin/python

import os
import sys
import subprocess



MANDETORY_PARM_COUNT = 3
NONE_COUNT = 0



def grep_exec(keyword, searchDir, filetype):

    grep_command = "grep -i " + keyword + " " + searchDir + "/*." + filetype
    cmd_result = subprocess.call(grep_command, stdin=None, stdout=None, stderr=subprocess.STDOUT, shell=True)

    return cmd_result 
   

def subprocess_open(keyword, searchDir, filetype):

    grep_command = "grep -i " + keyword + " " + searchDir + "/*." + filetype
    popen = subprocess.Popen(grep_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    (stdoutdata, stderrdata) = popen.communicate()

    return stdoutdata


 
def search(dir, keyword, filetype):

    try:
        files = os.listdir(dir)
        for file in files:
            fullFilename = os.path.join(dir, file)

            if os.path.isdir(fullFilename):
                #grep_exec(keyword, fullFilename, filetype)
                result = subprocess_open(keyword, fullFilename, filetype)
                if len(result) > NONE_COUNT:
                    print(result)
                search(fullFilename, keyword, filetype)

    except PermissionError:
        pass
 


def main():

    if len(sys.argv) < MANDETORY_PARM_COUNT:
        print("\n\t [usage] gr <keyword> <find path>\n")
        return -1

    searchDir = "."
    keyword = sys.argv[1]
    filetype = sys.argv[2]
    
    #grep_exec(keyword, searchDir, filetype)
    result = subprocess_open(keyword, searchDir, filetype)
    print(len(result))
    if len(result) > NONE_COUNT:
        print result

    search(searchDir, keyword, filetype)

    return 0



if __name__ == '__main__':
    main()
